### ISSUE TITLE
Найти параметр Max font size

### ISSUE THREAD

**Issue by kulakovt** [dm-logv/wordcloud-cli-dockerized#2]
Параметра `max_font_size` нет в [официальной документации к CLI](https://amueller.github.io/word_cloud/cli.html). Но он есть, если работать с кодом [напрямую](https://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud):

`WordCloud(max_font_size=40)`

Возможно документация устарела. Хотелось бы найти потерявшийся параметр.

**Comment by dmlogv** [comment]
Такого параметра в CLI нет. Сделал форк с веткой https://github.com/dm-logv/word_cloud/tree/cli-args, PR в апстрим: https://github.com/amueller/word_cloud/pull/527

Собранный из нее контейнер можно забрать в `docker pull dmlogv/wordcloud-cli-dockerized:cli-args`

**Comment by kulakovt** [comment]
@dm-logv , если ты там так разошёлся на славу, добавь пожалуйста в CLI параметр `random_state`. Он поможет делать одинаковые картинки для разных размеров. Тоже было бы очень полезно.

**Comment by dmlogv** [comment]
Я же разом добавил (почти) все недостающие параметры. Смотри `--help`:

- `--prefer_horizontal`
- `--scale`
- `--colormap`
- `--mode`
- `--max_words`
- `--min_font_size`
- `--max_font_size`
- `--font_step`
- `--random_state`
- `--no_normalize_plurals`
- `--repeat`

**Comment by kulakovt** [comment]
Спасибо! :tada:
